name: CD Vercel 

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      runner:
        description: 'Runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      VERCEL_TOKEN:
        required: true

jobs:
  deploy:
    name: Build & Deploy to Vercel
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy
        uses: org-test-reply-1/platform-actions/vercel-deploy@main
        with:
          node-version: ${{ inputs.node-version }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
